Module3 task1
htmlacademy-adaptive/1771277-pognali-22 pull request #5
Opened 2021-04-15 14:13 UTC by ufakrendel

2021-04-15 21:19 UTC, KirillKolomin commented on source/less/blocks/about.less
> +  font-family: "Blogger Sans", sans-serif;
а зачем здесь ты снова пишешь font-family? Ты ведь его уже объявил в .about?

2021-04-15 21:20 UTC, KirillKolomin commented on source/less/blocks/about.less
> +  padding-top: 19px;
объединяй padding/margin в одну строку

2021-04-15 21:21 UTC, KirillKolomin commented on source/less/blocks/adress.less
> +  font-family: "Blogger Sans", sans-serif;
Может быть тогда его на page__body повесить?

2021-04-15 21:22 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  display: block;
а разве это не display:block по умолчанию?

2021-04-15 21:22 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  display: block;
а разве это не display:block по умолчанию?

2021-04-15 21:23 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  margin: 0;
ты уверен, что хочешь сбрасывать стили только в этом элементе? Может вынести это в блок?

2021-04-15 21:26 UTC, KirillKolomin commented on source/less/blocks/feedback.less
> +  padding-left: 55px;
мне кажется или почти в каждом классе я вижу почти одинаковые padding-и? Можн их выделить в отдельный блок?

2021-04-15 21:27 UTC, KirillKolomin commented on source/less/blocks/page-footer.less
> +.page__footer {
почему файл называется page-footer, но здесь только page__?

2021-04-15 21:29 UTC, KirillKolomin commented on source/less/blocks/page.less
> +  display: flex;
Мне вот интересно, ты решил head спозиционировать над body?  И как ты увидишь результат, если head всегда скрыт?

2021-04-15 21:31 UTC, KirillKolomin commented on source/less/blocks/price.less
> +.price-item__description {
вижу стили в price-item__description и price-item__price повторяются. Можно это вынести в отдельный блок или написать хотябы .price-item__description, .price-item__price {...}?

2021-04-15 21:34 UTC, KirillKolomin commented on source/less/blocks/promo.less
> +  font-size: 16px;
Почти везде используешь font-size, color и т.д. Создай less миксин и подумай над тем, чтобы выделить в отдельный блок.

2021-04-15 21:35 UTC, KirillKolomin commented on source/less/constants.less
> +@basic-blue: #161c35;
отдельно должны быть просто цвета и отдельно bg, color и т.п, которым ты присваиваешь переменную с цветом

2021-04-15 21:37 UTC, KirillKolomin commented on source/less/style.less
> +}
зачем ты объявил 6 блоков свойств и по итогу остался только последний? Используй миксины.

2021-04-17 08:33 UTC, ufakrendel commented on source/less/style.less
> +}
Следовал примеру отсюда: https://proverstka.com.ua/services/podklyuchenie-shrifta-k-html-stranice/

2021-04-17 08:33 UTC, ufakrendel commented on source/less/constants.less
> +@basic-blue: #161c35;
Этот момент не понял. Поясни плз

2021-04-17 08:34 UTC, ufakrendel commented on source/less/blocks/about.less
> +  font-family: "Blogger Sans", sans-serif;
Шрифт повесил на page. Отовсюду постарался удалить. Задаю теперь только weight

2021-04-17 08:34 UTC, ufakrendel commented on source/less/blocks/business-prices.less
> +  display: block;
display:block вроде как везде поправил

2021-04-17 08:35 UTC, ufakrendel commented on source/less/blocks/business-prices.less
> +  margin: 0;
Вынес наверх

2021-04-17 08:35 UTC, ufakrendel commented on source/less/blocks/feedback.less
> +  padding-left: 55px;
Они местами плаваю на пиксель-два. Забить и брать среднее?

2021-04-17 08:35 UTC, ufakrendel commented on source/less/blocks/page-footer.less
> +.page__footer {
Поправил

2021-04-17 08:36 UTC, ufakrendel commented on source/less/blocks/page.less
> +  display: flex;
Чет не разобрался вообще с менюшкой. Не пойму как это должно нормально работать

2021-04-17 17:35 UTC, KirillKolomin commented on source/less/blocks/about.less
> +  width: 100%;
для чего здесь width and height: 100%?

2021-04-17 17:35 UTC, KirillKolomin commented on source/less/blocks/about.less
> +  width: 100%;
а также и margin and padding: 0?

2021-04-17 17:41 UTC, KirillKolomin commented on source/less/blocks/adress.less
> +  height: 100%;
зачем блочным элементам задавать это?

2021-04-17 17:42 UTC, KirillKolomin commented on source/less/blocks/adress.less
> +  height: 100%;
width and height: 100%?

2021-04-17 17:42 UTC, KirillKolomin commented on source/less/blocks/adress.less
> +  border-radius: 0 0 30px 30px;
где-то я это уже видел. Можно в отдельный блок вытащить?

2021-04-17 17:44 UTC, KirillKolomin commented on source/less/blocks/big-button.less
> +.big-button {
выглядит как модификатор а не как полноценный блок. должно быть button button--big

2021-04-17 17:46 UTC, KirillKolomin commented on source/less/blocks/price.less
> +  text-decoration: none;
text-decoration уже ведь есть для *

2021-04-17 17:46 UTC, KirillKolomin commented on source/less/blocks/big-button.less
> +  text-decoration: none;
text-decoration уже ведь есть для *

2021-04-17 17:49 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  margin: 0;
у тебя дивы с margin and padding по дефолту? Зачем это делать?

2021-04-17 17:50 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  list-style-type: none;
делай сброс стилей в style.less по тегу

2021-04-17 17:51 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  color: @special-grey;
Я вижу, что ты в каждом классе добавляешь стилей на шрифт сделай это через title блок с модификаторами --level-1, --level-2 и т.д. В телеге отправил статью, там смотри желтую таблицу для примера.

2021-04-17 17:52 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  color: @special-grey;
И мы обсуждали уже это? Если да то к чему пришли?

2021-04-17 17:52 UTC, KirillKolomin commented on source/less/blocks/business-prices.less
> +  margin: 0;
проверь на этот кейс весь проект

2021-04-17 17:54 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  padding: 25px 61px 82px 49px;
зачем на каждый подобный блок накидывать стилей на выравнивание?
Добавь какой-нибудь блок который будет это делать за тебя

2021-04-17 17:55 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  padding: 25px 61px 82px 49px;
Посмотри все подобные места
![image](https://user-images.githubusercontent.com/42203833/115122188-4cbda900-9fbf-11eb-9f3d-b3bfd946f772.png)

2021-04-17 17:56 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  padding: 25px 61px 82px 49px;
![Uploading image.png…]()

2021-04-17 17:56 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  padding: 25px 61px 82px 49px;
![image](https://user-images.githubusercontent.com/42203833/115122205-71198580-9fbf-11eb-8684-9242804546dc.png)

2021-04-17 17:58 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  padding: 25px 61px 82px 49px;
Выяви зависимость. И не занимайся perfect pixeling - это маразм. Если дизайнер не может запомнить свой отступы - это его проблемы.

2021-04-17 18:00 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  padding: 25px 61px 82px 49px;
Убери эти бесконечные padding. Мы же разработчики а не студенты, которые за пару тысяч сделают всё, что им скажут.

2021-04-17 18:02 UTC, KirillKolomin commented on source/less/style.less
> +}
Ок. вопросов нет

2021-04-20 15:20 UTC, ufakrendel commented on source/less/blocks/about.less
> +  width: 100%;
Поправил

2021-04-20 15:20 UTC, ufakrendel commented on source/less/blocks/adress.less
> +  height: 100%;
Для заливки углов.

2021-04-20 15:21 UTC, ufakrendel commented on source/less/blocks/adress.less
> +  border-radius: 0 0 30px 30px;
вынес в миксин

2021-04-20 15:21 UTC, ufakrendel commented on source/less/blocks/big-button.less
> +.big-button {
тоже убрал в миксины

2021-04-20 15:24 UTC, ufakrendel commented on source/less/blocks/business-prices.less
> +  margin: 0;
Ок.Принял

2021-04-20 15:25 UTC, ufakrendel commented on source/less/blocks/business-prices.less
> +  list-style-type: none;
Сделано

2021-04-20 15:26 UTC, ufakrendel commented on source/less/blocks/business-prices.less
> +  color: @special-grey;
Сделано

2021-04-20 15:26 UTC, ufakrendel commented on source/less/blocks/companions.less
> +  padding: 25px 61px 82px 49px;
Постараюсь лепить поменьше.

2021-04-27 06:25 UTC, KirillKolomin commented on source/less/blocks/about.less
> +  padding: 32px 60px 66px 50px;
Напомню.
Мы хотели переносить горизонтальные паддинги на текстовые блоки, но здесь опять обертки со всех сторон. Сначала центрируем по картинкам (на всех секшнах должны висеть эти центрующие), потом дожимаем текста через их блоки. Либо второй вариант, когда сжимаем всё, но расширяем картинки. Мне больше нравится первый вариант.
![image](https://user-images.githubusercontent.com/42203833/116194734-ead90e00-a739-11eb-9dcc-d063edcf0e69.png)

2021-04-27 06:31 UTC, KirillKolomin commented on source/less/blocks/font.less
> +.font__title-1 {
ты везде вешаешь font__title-?, но это не по БЭМ. Ты не можешь навешать элемент не имея блока выше. В данном случае нигде нет блока font

2021-04-27 06:32 UTC, KirillKolomin commented on source/less/blocks/font.less
> +.font__title-1 {
Сделай это всё просто блоками

2021-04-27 06:33 UTC, KirillKolomin commented on source/less/blocks/font.less
> +  padding-bottom: 20px;
почему в одном случае это padding-bottom, а в другом margin-bottom?

2021-04-27 06:50 UTC, KirillKolomin commented on source/less/blocks/about.less
> +.about {
Удали во всех местах жёстко заданные ширину и высоту. Они лишние.
![image](https://user-images.githubusercontent.com/42203833/116197876-f1698480-a73d-11eb-82cb-0636e55bd74e.png)

2021-04-27 07:02 UTC, KirillKolomin commented on source/less/blocks/directions.less
> +  padding: 62px 60px 0 50px;
мы договаривались о другом. Но что это значит, справа 60, слева 50? Зачем?

2021-04-27 07:06 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  margin-top: 16px;
для чего этот margin?

2021-04-27 07:07 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  color: @basic-white;
для чего этот color?

2021-04-27 07:09 UTC, KirillKolomin commented on source/less/blocks/companions.less
> +  margin-top: 16px;
Выглядит так, что переписав всё после нашей консультации ты не удалил старое. У меня была практика работать с коллегой, которая вообще не удаляла старый код. Приходило всё к тому, что она везде писала !important. Это было просто ужасно

2021-04-27 07:15 UTC, KirillKolomin commented on source/index.html
> +              <picture class="companion__picture">
вложил picture в picture

2021-04-27 07:15 UTC, KirillKolomin commented on source/index.html
> +              <picture class="companion__picture">
![Uploading image.png…]()

2021-04-27 07:16 UTC, KirillKolomin commented on source/index.html
> +              <picture class="companion__picture">
![image](https://user-images.githubusercontent.com/42203833/116200906-96399100-a741-11eb-8bc5-dc374b20b021.png)

2021-04-27 07:23 UTC, KirillKolomin commented on source/less/blocks/companion.less
> +  display: inline-flex;
почему inline-flex?

2021-04-27 07:27 UTC, KirillKolomin commented on source/less/blocks/companion.less
> +  display: inline-flex;
Как говорит мой нынешний коллега, который сейчас фулл раньше бэк. Это ничего не ломает тогда почему бы и нет, вкладывая label без инпута в див. Но сделав так, это усложняет процесс поддержки проекта. Потому, что придут чистые FE, которые скажут, что за говно, почему label в див и начнут искать скрытые смыслы тратя время на изучение ненужных файлов со стилями и т.п. Но если мы, что-то пишем то давай вкладывать в это правильный и чистый смысл.

2021-04-27 07:30 UTC, KirillKolomin commented on source/less/blocks/price.less
> +  display: grid;
Я вот не вижу смысла такому простому блоку давать дисплей грид.

2021-04-27 07:30 UTC, KirillKolomin commented on source/less/blocks/price.less
> +  display: grid;
Пройди https://codepip.com/games/flexbox-froggy/ . Поможет в понимании flexbox

2021-04-27 07:34 UTC, KirillKolomin commented on source/less/blocks/font.less
> +  .set-font(16px, 22px, 700);
если это называется bold, то почему это ещё обозначает размеры? Да ещё и font-style: normal, я вот вообще не увидел, чтобы в этом проекте где-то был бы font-style отличный от normal

2021-04-27 07:35 UTC, KirillKolomin commented on source/less/blocks/font.less
> +  .set-font(16px, 22px, 700);
Да ещё и padding-bottom

2021-04-27 07:36 UTC, KirillKolomin commented on source/less/blocks/font.less
> +  font-style: normal;
зачем здесь font-style?

2021-04-27 07:45 UTC, KirillKolomin commented on source/less/blocks/header.less
> +  width: calc(100% - 50px);
для чего?

2021-04-27 07:47 UTC, KirillKolomin commented on source/less/blocks/header.less
> +  width: calc(100% - 50px);
это из-за того, что ты накидал кучу разных стилей

2021-04-27 07:50 UTC, KirillKolomin commented on source/less/blocks/mixins.less
> +  &:active * {
давай без *

2021-04-27 07:50 UTC, KirillKolomin commented on source/less/blocks/font.less
> +.font__subtitle-bold-1 {
почему ты не заводил ....-bold-... для title с первого по 4-ый?

2021-04-30 16:59 UTC, andreysgra requested changes

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
>            </div>
Лишний закрывающий тег `</div>`.

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
> +                  width="36px"></img>
```suggestion
                <img class="country-list__img" src="img/flags/Czechia.png" alt="флаг страны" height="24"
                  width="36">
```

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
> +                <img class="country-list__img" alt="флаг страны" height="24px" width="36px"></img>
```suggestion
                <img class="country-list__img" alt="флаг страны" height="24" width="36">
```

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
> +          <a class="step-2__next-btn font-subtitle-b-1" href="#step-3"><span>Следующий шаг<span></a>
```suggestion
          <a class="step-2__next-btn font-subtitle-b-1" href="#step-3"><span>Следующий шаг</span></a>
```

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
> +          <p class="step-3__title font-title-b-5">Шаг 3.<br>Развлечения</p>
Нужно не ссылку ставить, а идентификатор на блок:
```suggestion
        <section class="add-plan__step-3 step-3" id="step-3">
          <p class="step-3__title font-title-b-5">Шаг 3.<br>Развлечения</p>
```

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
> +          <a class="step-3__back-btn font-subtitle-b-1" type="button" href="#step-2">На шаг назад</a>
```suggestion
          <a class="step-3__back-btn font-subtitle-b-1" href="#step-2">На шаг назад</a>
```

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
> +          </picture>
`<picture>` вложен в `<picture>`.

2021-04-30 16:59 UTC, andreysgra commented on source/form.html
> +          <span class="page-footer__created-by-text">Разработано<span>
```suggestion
          <span class="page-footer__created-by-text">Разработано</span>
```

2021-04-30 16:59 UTC, andreysgra commented on source/index.html
> +      <a class="header__login" href="login.html"><span class="font-subtitle-b-2">Авторизация<span></a>
```suggestion
      <a class="header__login" href="login.html"><span class="font-subtitle-b-2">Авторизация</span></a>
```

2021-04-30 16:59 UTC, andreysgra commented on source/index.html
> +          <a class="promo__navigation-login-btn" href="login.html"><span class="font-subtitle-b-2">Авторизация<span></a>
```suggestion
          <a class="promo__navigation-login-btn" href="login.html"><span class="font-subtitle-b-2">Авторизация</span></a>
```

2021-04-30 16:59 UTC, andreysgra commented on source/index.html
> +              <img src="img/firsova-mark.png" width="60px" width="60px" alt="Рейтинг">
```suggestion
              <img src="img/firsova-mark.png" width="60" height="60" alt="Рейтинг">
```

2021-04-30 16:59 UTC, andreysgra commented on source/index.html
> +              <img src="img/demin-mark.png" width="60px" width="60px" alt="Рейтинг">
```suggestion
              <img src="img/demin-mark.png" width="60" height="60" alt="Рейтинг">
```

2021-04-30 16:59 UTC, andreysgra commented on source/index.html
> +              <svg cclass="contact-list__item-img" viewBox="0 0 45 45" fill="black" width="45px" height="45px">
```suggestion
              <svg class="contact-list__item-img" viewBox="0 0 45 45" fill="black" width="45px" height="45px">
```

2021-04-30 16:59 UTC, andreysgra commented on source/index.html
> +          </picture>
`<picture>` вложен в `<picture>`.

2021-04-30 16:59 UTC, andreysgra commented on source/index.html
> +          <span class="page-footer__created-by-text">Разработано<span>
```suggestion
          <span class="page-footer__created-by-text">Разработано</span>
```

2021-05-01 18:11 UTC, merged